In [10]:
import numpy
from numpy import array
from pyspark.mllib.clustering import KMeans

Load Data

In [11]:
data = sc.textFile("test.txt")

In [12]:
data.collect()

[u'0.0 0.0 0.0',
 u'0.1 0.1 0.1',
 u'0.2 0.2 0.2',
 u'9.0 9.0 9.0',
 u'9.1 9.1 9.1',
 u'9.2 9.2 9.2']

In [13]:
parsed_data = data.map(lambda line: array([float(x) for x in line.split(' ')]))

In [14]:
parsed_data.collect()

[array([0., 0., 0.]),
 array([0.1, 0.1, 0.1]),
 array([0.2, 0.2, 0.2]),
 array([9., 9., 9.]),
 array([9.1, 9.1, 9.1]),
 array([9.2, 9.2, 9.2])]

In [16]:
clusters = KMeans.train(parsed_data, 2, maxIterations=10)

In [17]:
clusters.predict(parsed_data).collect()

[0, 0, 0, 1, 1, 1]